spring.application.name=orderservice

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/orderdb
spring.datasource.username=root
spring.datasource.password=Zee@23wins

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true